spring:
  application:
    name: frontend-service

server:
  port : 9091

zipkin:
  host: ${ZIPKIN_HOST:localhost}
  port: ${ZIPKIN_PORT:9411}

#used by the client of grpc to connect to grpc server.
quote-service:
  host: ${QUOTE_HOST:quote}
  port: ${QUOTE_PORT:50051}

vote-service:
  host: ${VOTE_HOST:votes}
  port: ${VOTE_PORT:50052}

logging:
  level:
    org.bal: INFO
    org.springframework: INFO


