spring:
  application:
    name: frontend-service
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: ${ZIPKIN_SVC_HOST:"http://localhost:9411"}
  sleuth:
    sampler:
      rate: ${SLEUTH_SAMPLING_RATE:10}
    web:
      skip-pattern: "/healthz"

management:
  metrics:
    enable:
      jvm: true
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'


server:
  port : 9091


#used by the client of grpc to connect to grpc server.
quote-server:
  host: ${QUOTE_SVC_HOST:quotes}
  port: ${QUOTE_SVC_PORT:50051}

vote-server:
  host: ${VOTE_SVC_HOST:votes}
  port: ${VOTE_SVC_PORT:50052}

logging:
  pattern:
    console: "%d [%X{traceId}/%X{spanId}] [%thread] %-5level %logger{36} - %m %replace(%xException){'\n','\u2028'}%nopex%n"
  level:
    org.bal: DEBUG
    org.springframework: INFO
    root: INFO