server:
  port : 9091
#app.name: %project.artifactId%

zipkin:
  host: ${ZIPKIN_HOST:localhost}
  port: ${ZIPKIN_PORT:9411}

#used by the client of grpc to connect to grpc server.
person-service:
  host: ${PERSON_SERVICE_HOST:localhost}
  port: ${PERSON_SERVICE_PORT:50051}

logging:
  level:
    ROOT: DEBUG

#prometheus and spring actuator
endpoints:
  metrics:
    id: springmetrics
    sensitive: false
    enabled: true
  prometheus:
    id: metrics
    enabled: true
    sensitive: false

