spring:
  application:
    name: frontend-service

server:
  port : 9091

zipkin-server:
  host: ${ZIPKIN_SVC_HOST:localhost}
  port: ${ZIPKIN_SVC_PORT:9411}
  samplingRate: ${ZIPKIN_SAMPLING_RATE:0.1}

#used by the client of grpc to connect to grpc server.
quote-server:
  host: ${QUOTE_SVC_HOST:quotes}
  port: ${QUOTE_SVC_PORT:50051}

vote-server:
  host: ${VOTE_SVC_HOST:votes}
  port: ${VOTE_SVC_PORT:50052}

logging:
  level:
    org.bal: DEBUG
    org.springframework: INFO


