server:
  port : 8888

spring:
  zipkin:
    baseUrl: ${ZIPKIN_SERVER_HOST:"http://localhost:9411"}
  main:
    allow-bean-definition-overriding: true

management:
  metrics:
    use-global-registry: true
    enable:
      jvm: true
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'


grpc:
    port : 50052
    enableReflection: true

logging:
  pattern:
    console: "%d [%X{traceId}/%X{spanId}] [%thread] %-5level %logger{36} - %m %replace(%xException){'\n','\u2028'}%nopex%n"
  level:
    org.bal: DEBUG


quotes-server:
  host: ${QUOTE_SERVER_HOST:localhost}
  port: ${QUOTE_SERVER_PORT:50051}

redis-server:
  host: ${REDIS_SERVER_HOST:votes-db-service}
  port: ${REDIS_SERVER_PORT:6379}
  password: ${REDIS_PASSWORD:dummy}