server:
  port : 8888

management:
  metrics:
    enable:
      jvm: true
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
grpc:
    port : 50052
    enableReflection: true

logging:
  level:
    ROOT: DEBUG

zipkin-server:
  host: ${ZIPKIN_SERVER_HOST:localhost}
  port: ${ZIPKIN_SERVER_PORT:9411}

quotes-server:
  host: ${QUOTE_SERVER_HOST:localhost}
  port: ${QUOTE_SERVER_PORT:50051}

redis-server:
  host: ${REDIS_SERVER_HOST:redis}
  port: ${REDIS_SERVER_PORT:6379}
  password: ${REDIS_PASSWORD}