grpc:
    port : 50052
    enableReflection: true

logging:
  level:
    ROOT: DEBUG

zipkin-server:
  host: ${ZIPKIN_HOST:localhost}
  port: ${ZIPKIN_PORT:9411}

quotes-server:
  host: ${QUOTE_HOST:localhost}
  port: ${QUOTE_PORT:50051}

redis-server:
  host: ${REDIS_SERVER_HOST:redis}
  port: ${REDIS_SERVER_PORT:6379}
  password: ${REDIS_PASSWORD}