apiVersion: skaffold/v1beta15
kind: Config
profiles:
- name: local
  build:
    insecureRegistries: ["localhost:32000"]
    artifacts:
      - image: localhost:32000/bot-go
        context: .
        docker:
          dockerfile: Dockerfile
        
        # custom:
        #   buildCommand: make
        #   dependencies:
        #     dockerfile:
        #       path: Dockerfile
    local:
      push: true
      useDockerCLI: true
      
  deploy:
    kubectl:
      manifests:
      - src/k8s-manifests/local/*.yaml

