apiVersion: skaffold/v1beta15
kind: Config
profiles:
- name: local
  build:
    insecureRegistries: ["localhost:32000"]
    tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"    
    artifacts:
    - image: localhost:32000/bot-go
      custom:
        buildCommand: ./build.sh
        dependencies:
          paths:
          - .
    local:
      push: true
- name: remote
  build:
    tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"    
    artifacts:
    - image: balchu/bot-go
      custom:
        buildCommand: ./build.sh
        dependencies:
          paths:
          - .
    local:
      push: true    
  deploy:
    kubectl:
      manifests:
      - src/k8s-manifests/local/*.yaml

