apiVersion: skaffold/v1beta11
kind: Config
profiles:
- name: local
  build:
    insecureRegistries: ["localhost:32000"]
    artifacts:
      - image: localhost:32000/frontend
        context: .
        jibMaven: {}
    local:
      push: true
      useDockerCLI: true
  deploy:
    kubectl:
      manifests:
      - src/main/k8s-config/local/*.yaml
