apiVersion: skaffold/v1beta13
kind: Config
profiles:
- name: do
  build:
    artifacts:
      - image: balchu/frontend
        context: .
        jibMaven: {}
    local:
      push: true
      useDockerCLI: true
  deploy:
    kubectl:
      manifests:
        - src/k8s-manifests/do/*.yaml

- name: local
  build:
    artifacts:
      - image: localhost:32000/frontend
        context: .
        jibMaven: {}
    local:
      push: true
      useDockerCLI: true
  deploy:
    helm:
      releases:
      - name: frontend
        chartPath: frontend-charts
        namespace: my-project
        wait: true
        valuesFiles:
          - frontend-charts/values-default.yaml
          - frontend-charts/values-local.yaml
        values:
          image.repository: localhost:32000/frontend

