apiVersion: skaffold/v2beta13
kind: Config
profiles:
- name: local
  build:
    artifacts:
    - image: localhost:32000/frontend
      context: .
      jib: {}
    local:
      push: true
  deploy:
    helm:
      releases:
      - name: frontend
        chartPath: frontend-charts
        valuesFiles:
        - frontend-charts/values-default.yaml
        - frontend-charts/values-local.yaml
        artifactOverrides:
          image.repository: localhost:32000/frontend
        namespace: my-project
        wait: true
- name: do
  build:
    artifacts:
    - image: balchu/frontend
      context: .
      jib: {}
    local:
      push: true
  deploy:
    helm:
      releases:
      - name: frontend
        chartPath: frontend-charts
        valuesFiles:
        - frontend-charts/values-default.yaml
        - frontend-charts/values-do.yaml
        artifactOverrides:
          image.repository: balchu/frontend
        namespace: my-project
        wait: true
