apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
    - image: balchu/demo
      context: .
      jibMaven: {}
  local:
    push: false
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - src/main/k8s-config/do/dev-install.yaml
