---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bot
  namespace: my-project
  labels:
    app.kubernetes.io/name: bot
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: bot
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        kubernetes.io/change-cause: "Update to bot artifact version 2.0.0 test"
      labels:
        app.kubernetes.io/name: bot
    spec:
      containers:
      - name: bot
        image: balchu/bot:2.0.0
        imagePullPolicy: Always
        env:
          - name: ZIPKIN_SERVER_HOST
            valueFrom:
              configMapKeyRef:
                name: bot-config
                key: zipkin-host
          - name: ZIPKIN_SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: bot-config
                key: zipkin-port
          - name: FRONTEND_SERVER_HOST
            valueFrom:
              configMapKeyRef:
                name: bot-config
                key: frontend-host
          - name: FRONTEND_SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: bot-config
                key: frontend-port
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
