apiVersion: skaffold/v1
kind: Config
profiles:
- name: local
  build:
    artifacts:
    - image: localhost:32000/quotes
      context: .
      jib: {}
    local:
      push: true
      useDockerCLI: true
  deploy:
    helm:
      releases:
      - name: quotes
        chartPath: quote-charts
        namespace: my-project
        wait: true
        valuesFiles:
        - quote-charts/values-default.yaml
        - quote-charts/values-local.yaml
        values:
          image.repository: localhost:32000/quotes

- name: do
  build:
    artifacts:
    - image: balchu/quotes
      context: .
      jib: {}
    local:
      push: true
      useDockerCLI: true
  deploy:
    helm:
      releases:
      - name: quotes
        chartPath: quote-charts
        namespace: my-project
        wait: true
        valuesFiles:
        - quote-charts/values-default.yaml
        - quote-charts/values-do.yaml
        values:
          image.repository: balchu/quotes

- name: quotes-db-local
  deploy:
    helm:
      releases:
        - name: quotes-db
          chartPath: quotes-db-charts
          namespace: my-project
          wait: true
          valuesFiles:
            - quotes-db-charts/values-default.yaml
            - quotes-db-charts/values-local.yaml

- name: quotes-db-do
  deploy:

    helm:
      releases:
        - name: quotes-db
          chartPath: quotes-db-charts
          namespace: my-project
          wait: true
          valuesFiles:
            - quotes-db-charts/values-default.yaml
            - quotes-db-charts/values-do.yaml
