apiVersion: skaffold/v1beta13
kind: Config
profiles:
- name: do
  build:
    artifacts:
      - image: balchu/quotes
        context: .
        jibMaven: {}
    local:
      push: true
      useDockerCLI: true
  deploy:
    kubectl:
      manifests:
        - src/k8s-manifests/do/*.yaml

- name: local
  build:
    artifacts:
      - image: localhost:32000/quotes
        context: .
        jibMaven: {}
    local:
      push: true
      useDockerCLI: true
  deploy:
    helm:
      releases:
      - name: quotes
        chartPath: quote-charts
        namespace: my-project
        wait: true
        valuesFiles:
        - quote-charts/values-local.yaml
        values:
          image.repository: localhost:32000/quotes

