kind: ConfigMap
apiVersion: v1
metadata:
  name:  {{ template "frontend.name" . }}
  namespace: {{.Release.Namespace}}
data:
  zipkin-host: {{ .Values.zipkin.host }}
  quote-service-host: {{ .Values.quotes.host }}
  quote-service-port: {{ .Values.quotes.port | quote }}
  sleuth-sampling-rate: {{ .Values.sleuth.sampling | quote }}
  vote-service-host: {{ .Values.votes.host }}
  vote-service-port: {{ .Values.votes.port | quote }}
