apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "frontend.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "public"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "frontend.name" . }}
          servicePort: {{ .Values.service.port }}
