apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "frontend.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "public"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ template "frontend.name" . }}
              port:
                number: {{ .Values.service.port }}
