apiVersion: v1
kind: Secret
metadata:
  name: {{ template "frontend.name" . }}
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  keycloak-client-secret: {{ .Values.keycloak.clientSecret | b64enc }}
