apiVersion: v1
kind: Secret
metadata:
  name: {{ template "frontend.name" . }}
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  oauth2-client-secret: {{ .Values.oauth2.clientSecret | b64enc }}
