server:
  port : 9090
#app.name: %project.artifactId%

zipkin:
  host: ${ZIPKIN_HOST}
  port: ${ZIPKIN_PORT}

#used by the client of grpc to connect to grpc server.
person-service:
  host: ${PERSON_SERVICE_HOST}
  port: ${PERSON_SERVICE_PORT}

logging:
  level:
    ROOT: INFO