kind: ConfigMap
apiVersion: v1
metadata:
  name: demo-config
  namespace: do-myproject
data:
  zipkin-host: zipkin
  zipkin-port: "9411"
  person-service-host: grpc-service
  person-service-port: "9999"