---
kind: Service
apiVersion: v1
metadata:
  name: demo
  namespace: do-myproject
  labels:
    app: demo
  annotations:
      prometheus.io/scrape: 'false'
spec:
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9091
    name: http
  selector:
    app: demo
