---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo
  namespace: do-myproject
  labels:
    run: demo
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
      matchLabels:
        run: demo
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "demo version 1.2.5"
      labels:
        run: demo
    spec:
      containers:
      - name: demo
        image: balchu/demo:1.2.5
        ports:
        - containerPort: 9090
          protocol: TCP
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9090
        resources:
          limits:
            memory: 512M
            cpu: 1000m
          requests:
            memory: 256M
            cpu: 500m
        env:
          - name: TZ
            value: Asia/Singapore
          - name: ZIPKIN_HOST
            valueFrom:
              configMapKeyRef:
                name: demo-config
                key: zipkin-host
          - name: ZIPKIN_PORT
            valueFrom:
              configMapKeyRef:
                name: demo-config
                key: zipkin-port
          - name: PERSON_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: demo-config
                key: person-service-host
          - name: PERSON_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: demo-config
                key: person-service-port
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
