---
kind: Service
apiVersion: v1
metadata:
  name: votes
  namespace: my-project
  labels:
    app.kubernetes.io/name: votes
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8888"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 50052
    name: grpc
  - protocol: TCP
    port: 8888
    name: http

  selector:
    app.kubernetes.io/name: votes
