apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zipkin-ingress
  namespace: my-project
  annotations:
    kubernetes.io/ingress.class: "public"
spec:
  rules:
  - host: zipkin.10.152.183.83.nip.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: zipkin
              port:
                number: 9411
