apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zipkin
  namespace: my-project
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: zipkin.example.local
    http:
      paths:
      - path: /
        backend:
          serviceName: zipkin
          servicePort: 9411
