spring:
  application:
    name: bot-voter
    castVoteFixedRate: 2000
    listQuotesFixedRate: 1000
    tallyVotesFixedRate: 500
frontend-server:
  port : ${FRONTEND_SERVER_PORT:31002}
  host: ${FRONTEND_SERVER_HOST:frontend}

zipkin-server:
  host: ${ZIPKIN_SERVER_HOST:127.0.0.1}
  port: ${ZIPKIN_SERVER_PORT:9411}
  samplingRate: ${ZIPKIN_SAMPLING_RATE:0.1}

logging:
  level:
    org.bal: INFO
    org.springframework: INFO
