spring:
  application:
    name: bot-voter
    castVoteFixedRate: 2000
    listQuotesFixedRate: 1000

server:
  port : ${FRONTEND_PORT:31002}
  host: ${FRONTEND_HOST:frontend}

zipkin:
  host: ${ZIPKIN_HOST:127.0.0.1}
  port: ${ZIPKIN_PORT:9411}
  samplingRate: ${ZIPKIN_SAMPLING_RATE:0.1}

logging:
  level:
    org.bal: INFO
    org.springframework: INFO
