kind: ConfigMap
apiVersion: v1
metadata:
  name:  {{ template "quotes.name" . }}
  namespace: {{.Release.Namespace}}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  zipkin-server-host: {{ .Values.zipkin.host }}
  zipkin-server-port: {{ .Values.zipkin.port | quote }}
  quotes-db-user: {{ .Values.db.user }}