apiVersion: v1
kind: Secret
metadata:
  name: {{ template "votes.name" . }}
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  redis_password: {{ .Values.redis.password | b64enc }}
  sentry-dsn: {{ .Values.sentry.client_dsn | b64enc }}
