---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo
  namespace: my-project
  labels:
    run: demo
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: demo
  template:
    metadata:
      labels:
        run: demo
    spec:
      containers:
      - name: demo
        image: demo:1.0.1
        ports:
        - containerPort: 9090
          protocol: TCP
        imagePullPolicy: IfNotPresent
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /
            port: 9090
        env:
          - name: ZIPKIN_HOST
            valueFrom:
              configMapKeyRef:
                name: demo-config
                key: zipkin-host
          - name: ZIPKIN_PORT
            valueFrom:
              configMapKeyRef:
                name: demo-config
                key: zipkin-port
          - name: PERSON_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: demo-config
                key: person-service-host
          - name: PERSON_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: demo-config
                key: person-service-port
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
