apiVersion: v1
kind: Service
metadata:
  name: votes-db-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app.kubernetes.io/name: votes-db