---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: quotes
  namespace: my-project
  labels:
    app.kubernetes.io/name: quotes
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: quotes
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        kubernetes.io/change-cause: "Update to demo artifact version 1.1.0 test"
      labels:
        app.kubernetes.io/name: quotes
    spec:
      containers:
      - name: quote
        image: localhost:32000/quotes
        ports:
        - containerPort: 50051
          protocol: TCP
        - containerPort: 8888
          protocol: TCP
        readinessProbe:
          exec:
            command: ["/tools/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/tools/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 10

        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        env:
          - name: ZIPKIN_SERVER_HOST
            valueFrom:
              configMapKeyRef:
                name: quote-config
                key: zipkin-server-host
          - name: ZIPKIN_SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: quote-config
                key: zipkin-server-port
          - name: QUOTES_DB_USER
            valueFrom:
              configMapKeyRef:
                name: quote-config
                key: quotes-db-user
          - name: QUOTES_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: quotes-secrets
                key: quotes-db-password

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
