---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: quote
  namespace: my-project
  labels:
    app.kubernetes.io/name: quote
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: quote
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        kubernetes.io/change-cause: "Update to demo artifact version 1.1.0 test"
      labels:
        app.kubernetes.io/name: quote
    spec:
      containers:
      - name: quote
        image: localhost:32000/quotes
        ports:
        - containerPort: 50051
          protocol: TCP
        imagePullPolicy: IfNotPresent
        env:
          - name: ZIPKIN_HOST
            valueFrom:
              configMapKeyRef:
                name: quote-config
                key: zipkin-host
          - name: ZIPKIN_PORT
            valueFrom:
              configMapKeyRef:
                name: quote-config
                key: zipkin-port
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
