grpc:
    port : 50051
    enableReflection: true

logging:
  level:
    ROOT: INFO

zipkin-server:
  host: ${ZIPKIN_SERVER_HOST:localhost}
  port: ${ZIPKIN_SERVER_PORT:9411}

## default connection pool
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://postgres:5432/quotesdb
    username: postgresadmin
    password: admin123
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

