server:
  port : 8888

management:
  metrics:
    enable:
      jvm: true
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
grpc:
    port : 50051
    enableReflection: true

logging:
  level:
    ROOT: INFO

zipkin-server:
  host: ${ZIPKIN_SERVER_HOST:localhost}
  port: ${ZIPKIN_SERVER_PORT:9411}

## default connection pool
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://postgres:5432/quotesdb
    username: ${QUOTES_DB_USER:postgresadmin}
    password: ${QUOTES_DB_PASSWORD:dummy}
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

