server:
  port : 8888

management:
  metrics:
    enable:
      jvm: true
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
grpc:
    port : 50051
    enableReflection: true

logging:
  pattern:
    console: "%d [%X{traceId}/%X{spanId}] [%thread] %-5level %logger{36} - %m %nopex%n"
  level:
    org.bal: DEBUG

## default connection pool
spring:
  application:
    name: quote-service
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://quotes-db-service:5432/quotesdb
    username: ${QUOTES_DB_USER:postgresadmin}
    password: ${QUOTES_DB_PASSWORD:dummy}
  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  zipkin:
    baseUrl: ${ZIPKIN_SERVER_HOST:"http://localhost:9411"}

sentry:
  dsn: ${SENTRY_DSN}
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: debug

