apiVersion: skaffold/v1beta11
kind: Config
profiles:
- name: local
  deploy:
    kubectl:
      manifests:
        - postgres/postgres.yaml
        - redis/redis.yaml
        - schema-migrate/*.yaml
- name: do
  deploy:
    kubectl:
      manifests:
        - postgres/postgres-do.yaml
        - redis/redis-do.yaml

