kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "demo.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: demo
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "demo.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: {{ .Values.service.protocol }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /health
            port: {{ .Values.service.internalPort }}
        env:
          - name: ZIPKIN_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ template "demo.fullname" . }}
                key: zipkin-host
          - name: ZIPKIN_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ template "demo.fullname" . }}
                key: zipkin-port
          - name: PERSON_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ template "demo.fullname" . }}
                key: person-service-host
          - name: PERSON_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ template "demo.fullname" . }}
                key: person-service-port
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
