apiVersion: skaffold/v1beta13
kind: Config
profiles:
- name: local
  build:
    artifacts:
      - image: localhost:32000/votes
        context: .
        jibMaven: {}
    local:
      push: true
      useDockerCLI: true
  deploy:
    kubectl:
      manifests:
        - src/k8s-manifests/local/*.yaml
- name: do
  build:
    artifacts:
      - image: balchu/votes
        context: .
        jibMaven: {}
    local:
      push: true
      useDockerCLI: true
  deploy:
    kubectl:
      manifests:
        - src/k8s-manifests/do/*.yaml
