apiVersion: skaffold/v1beta13
kind: Config
profiles:
- name: local
  build:
    artifacts:
    - image: localhost:32000/votes
      context: .
      jibMaven: {}
    local:
      push: true
      useDockerCLI: true
  deploy:
    helm:
      releases:
      - name: votes
        chartPath: vote-charts
        namespace: my-project
        wait: true
        valuesFiles:
        - vote-charts/values-default.yaml
        - vote-charts/values-local.yaml
        values:
          image.repository: localhost:32000/votes

- name: do
  build:
    artifacts:
    - image: balchu/votes
      context: .
      jibMaven: {}
    local:
      push: true
      useDockerCLI: true
  deploy:
    helm:
      releases:
      - name: votes
        chartPath: vote-charts
        namespace: my-project
        wait: true
        valuesFiles:
        - vote-charts/values-default.yaml
        - vote-charts/values-do.yaml
        values:
          image.repository: balchu/votes

- name: votes-db-local
  deploy:
    helm:
      releases:
        - name: votes-db
          chartPath: votes-db-charts
          namespace: my-project
          wait: true
          valuesFiles:
            - votes-db-charts/values-default.yaml
            - votes-db-charts/values-local.yaml

- name: votes-db-do
  deploy:
    helm:
      releases:
        - name: votes-db
          chartPath: votes-db-charts
          namespace: my-project
          wait: true
          valuesFiles:
            - votes-db-charts/values-default.yaml
            - votes-db-charts/values-do.yaml

