apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
    - image: localhost:32000/votes
      context: .
      jibMaven: {}
  local:
    push: true
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - src/k8s-manifests/*.yaml
