apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: my-project
  labels:
    app: postgres
data:
  POSTGRES_DB: quotesdb
  POSTGRES_USER: postgresadmin
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: my-project
type: Opaque
data:
  POSTGRES_PASSWORD: YWRtaW4xMjM=

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: my-project
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: my-project
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: my-project
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    app: postgres

---
# connect to psql
# psql -h localhost -U postgresadmin --password -p 5432 quotesdb