apiVersion: skaffold/v1
kind: Config
profiles:
- name: local
  build:
    insecureRegistries: ["localhost:32000"]
    artifacts:
      - image: localhost:32000/bot
        context: .
        jib: {}
    local:
      push: true
      useDockerCLI: true
  deploy:
    kubectl:
      manifests:
      - src/k8s-manifests/local/*.yaml
- name: do
  build:
    artifacts:
      - image: balchu/bot
        context: .
        jib: {}
    local:
      push: true
      useDockerCLI: false
  deploy:
    kubectl:
      manifests:
        - src/k8s-manifests/do/*.yaml
