name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./bot-go/ --file bot-go/Dockerfile --tag demo-bot-go:$(date +%s)
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
          # Artifact name
          name: demo-bot-go
          # Directory containing files to upload
          path: /go/src/bot/bot
