name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker login
      run: echo '${{ secrets.DOCKERHUB_PASS }}' | docker login --username balchu --password-stdin

    - name: Get Skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && chmod uo+x skaffold && sudo mv skaffold /usr/local/bin
        skaffold version

    - name: Build the bot-go
      run: |
        export KO_DOCKER_REPO=docker.io/balchu/
        export IMAGE_TAG=latest
        cd bot-go
        skaffold build -p remote  | tee build-log.txt
          
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
          # Artifact name
          name: build-log
          # Directory containing files to upload
          path: build-log.txt

